import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/styles/tw.css";
import Header from "@/components/elements/Header";
import SessionProviderWrapper from "@/components/providers/SessionProviderWrapper";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {



    return (
        <html lang="en">
        <SessionProviderWrapper>
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {!["/auth/register", "/auth/login"].includes("router.pathname") && <Header />}

            {children}
        </body>
        </SessionProviderWrapper>
        </html>
    );
}
